from tkinter import *

def savedata():
    serialno_info = serialnoentry.get()
    modelno_info = modelnoentry.get()
    manufacturer_info = manufacturerentry.get()
    serviceengineer_info = serviceengineerentry.get()
    manager_info = managerentry.get()
    hsnsac_info = hsnsacentry.get()
    supplier_info = supplier.get()
    servicecentername_info = servicecenternameentry.get()
    servicecenteraddress_info = servicecenteraddressentry.get()
    warrantystartdate_info  = warrantystartdateentry.get()
    warrantyenddate_info = warrantyenddateentry.get()
    preventivemaintenance_info = preventivemaintenanceentry.get()
    price_info = priceentry.get()

    print(serialno_info)
    print(modelno_info)
    print(manufacturer_info)
    print(serviceengineer_info)
    print(manager_info)
    print(hsnsac_info)
    print(supplier_info)
    print(servicecentername_info)
    print(servicecenteraddress_info)
    print(warrantystartdate_info)
    print(warrantyenddate_info)
    print(preventivemaintenance_info)
    print(price_info)

    file = open("user.txt", "w")
    file.write("Serial No:" + serialno_info)
    file.write("\n")
    file.write("Model No:" + modelno_info)
    file.write("\n")
    file.write("Manufacturer :" + manufacturer_info)
    file.write("\n")
    file.write("Service Engineer:" + serviceengineer_info)
    file.write("\n")
    file.write("Manager:" + manager_info)
    file.write("\n")
    file.write("HSN / SAC:" + hsnsac_info)
    file.write("\n")
    file.write("Supplier:" + supplier_info)
    file.write("\n")
    file.write("Service Center Name:" + servicecentername_info)
    file.write("\n")
    file.write("Service Center Address:" + servicecenteraddress_info)
    file.write("\n")
    file.write("Warrantry Start Date:" + warrantystartdate_info)
    file.write("\n")
    file.write("Warranty End Date:" + warrantyenddate_info)
    file.write("\n")
    file.write("Preventive Maintenence:" + preventivemaintenance_info)
    file.write("\n")
    file.write(("Price:" + price_info)
    file.close()

root=Tk()

root.geometry("800x600")

root.title("Medical Data Entry Software")

Label(root,text="MEDICAL DEVICES ENTRY FORM",bg="skyblue",fg="black",font="arial 15 bold").grid(row=0,column=2)

serialno=Label(root,text="SERIAL NO:",font="calibri 11 bold")
modelno=Label(root,text="MODEL NO:",font="calibri 11 bold")
manufacturer=Label(root,text="MANUFACTURER:",font="calibri 11 bold")
serviceengineer=Label(root,text="SERVICE ENGINEER:",font="calibri 11 bold")
manager=Label(root,text="MANAGER:",font="calibri 11 bold")
hsnsac=Label(root,text="HSN / SAC:",font="calibri 11 bold")
supplier=Label(root,text="SUPPLIER:",font="calibri 11 bold")
servicecentername=Label(root,text="SERVICE CENTER NAME:",font="calibri 11 bold")
servicecenteraddress=Label(root,text="SERVICE CENTER ADDRESS:",font="calibri 11 bold")
warrantystartdate=Label(root,text="Warranty Start Date:",font="calibri 11 bold")
warrantyenddate=Label(root,text="Warranty End Date:",font="calibri 11 bold")
preventivemaintenance=Label(root,text="PREVENTIVE MAINTENANCE:",font="calibri 11 bold")
price=Label(root,text="PRICE:",font="calibri 11 bold")

serialno.grid(row=1,column=1)
modelno.grid(row=2,column=1)
manufacturer.grid(row=3,column=1)
serviceengineer.grid(row=4,column=1)
manager.grid(row=5,column=1)
hsnsac.grid(row=6,column=1)
supplier.grid(row=7,column=1)
servicecentername.grid(row=8,column=1)
servicecenteraddress.grid(row=9,column=1)
warrantystartdate.grid(row=10,column=1)
warrantyenddate.grid(row=11,column=1)
preventivemaintenance.grid(row=12,column=1)
price.grid(row=13,column=1)

serialnovalue=IntVar()
modelnovalue=IntVar()
manufacturervalue=StringVar()
serviceengineervalue=StringVar()
managervalue=StringVar()
hsnsacvalue=StringVar()
suppliervalue=StringVar()
servicecenternamevalue=StringVar()
servicecenteraddressvalue=StringVar()
warrantystartdatevalue=StringVar()
warrantyenddatevalue=StringVar()
preventivemaintenancevalue=StringVar()
pricevalue=IntVar()

serialnoentry=Entry(root,textvariable=serialnovalue)
modelnoentry=Entry(root,textvariable=modelnovalue)
manufacturerentry=Entry(root,textvariable=manufacturervalue)
serviceengineerentry=Entry(root,textvariable=serviceengineervalue)
managerentry=Entry(root,textvariable=managervalue)
hsnsacentry=Entry(root,textvariable=hsnsacvalue)
supplierentry=Entry(root,textvariable=suppliervalue)
servicecenternameentry=Entry(root,textvariable=servicecenternamevalue)
servicecenteraddressentry=Entry(root,textvariable=servicecenteraddressvalue)
warrantystartdateentry=Entry(root,textvariable=warrantystartdatevalue)
warrantyenddateentry=Entry(root,textvariable=warrantyenddatevalue)
preventivemaintenanceentry=Entry(root,textvariable=preventivemaintenancevalue)
priceentry=Entry(root,textvariable=pricevalue)

serialnoentry.grid(row=1,column=2)
modelnoentry.grid(row=2,column=2)
manufacturerentry.grid(row=3,column=2)
serviceengineerentry.grid(row=4,column=2)
managerentry.grid(row=5,column=2)
hsnsacentry.grid(row=6,column=2)
supplierentry.grid(row=7,column=2)
servicecenternameentry.grid(row=8,column=2)
servicecenteraddressentry.grid(row=9,column=2)
warrantystartdateentry.grid(row=10,column=2)
warrantyenddateentry.grid(row=11,column=2)
preventivemaintenanceentry.grid(row=12,column=2)
priceentry.grid(row=13,column=2)

button=Button(root,text="Save",font="lucida 12 bold",bg="green",command=savedata)
button.grid(row=20,column=2)

root.mainloop()